### ISSUE TITLE
history addon in merged file missing

### ISSUE THREAD

**Issue by StSchulze** [ursgal/ursgal#65]
> Traceback (most recent call last):
>   File "merge_n_count.py", line 45, in <module>
>     main(input_files=file_lists)
>   File "merge_n_count.py", line 39, in main
>     engine = 'venndiagram',
>   File "/ursgal/ucontroller.py", line 3019, in visualize
>     output_file_name = output_file_name
>   File "/ursgal/ucontroller.py", line 2888, in execute_unode
>     force  = force
>   File "/ursgal/ucontroller.py", line 1007, in prepare_unode_run
>     self.input_file_dicts = self.generate_multi_file_dicts(input_file)
>   File "/ursgal/ucontroller.py", line 1187, in generate_multi_file_dicts
>     multiple_engines = True,
>   File "/ursgal/unode.py", line 679, in get_last_search_engine
>     multiple_engines=multiple_engines,
>   File "/ursgal/unode.py", line 576, in get_last_engine
>     for element in self.flatten_list(history_event['history_addon']['search_engines_of_merged_files']):
> KeyError: 'search_engines_of_merged_files'

The last steps of the pipeline are a merge, a filtering and another merge.
After the first merge, the history addon 'search_engines_of_merged_files' is there, after the filtering it is also still there, but after the merge of the filtered files, it is gone.
Any ideas?

**Comment by StSchulze** [comment]
solved by #66
