### ISSUE TITLE
pymzml ERROR

### ISSUE THREAD

**Issue by cguetot** [ursgal/ursgal#80]
Hi,

I got an error when I run command `nosetests`, and it is something related to `pymzml` .

````

..............................................................................................................................................................................................................................................................................................................................................................................................................................E............................................................................................................................................................................................
======================================================================
ERROR: Failure: Exception (Filename has .gz extension but is missing the gzip magic bytes.
The file may be corrupted or not gzipped.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/carlos/.local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/carlos/.local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/carlos/.local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/carlos/.local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/carlos/Software/ursgal/tests/complete_search_with_omssa_test.py", line 65, in <module>
    force      = True
  File "/home/carlos/Software/ursgal/ursgal/ucontroller.py", line 1847, in search
    force = force,
  File "/home/carlos/Software/ursgal/ursgal/ucontroller.py", line 899, in convert
    output_file_name = output_file_name
  File "/home/carlos/Software/ursgal/ursgal/ucontroller.py", line 351, in convert_to_mgf_and_update_rt_lookup
    force, engine_name, answer
  File "/home/carlos/Software/ursgal/ursgal/ucontroller.py", line 2186, in run_unode_if_required
    json_path = json_path,
  File "/home/carlos/Software/ursgal/ursgal/unode.py", line 1387, in run
    report['execution'] = self._execute()
  File "/home/carlos/Software/ursgal/ursgal/wrappers/mzml2mgf_2_0_0.py", line 71, in _execute
    precursor_max_charge  = self.params['translations']['precursor_max_charge'],
  File "/home/carlos/Software/ursgal/ursgal/resources/platform_independent/arc_independent/mzml2mgf_2_0_0/mzml2mgf_2_0_0.py", line 113, in main
    peaks_2_write = spec.peaks('centroided')
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/spec.py", line 1017, in peaks
    mz_params = self._get_encoding_parameters('m/z array')
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/spec.py", line 199, in _get_encoding_parameters
    array_type_accession = self.calling_instance.OT[array_type]['id']
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/obo.py", line 109, in __getitem__
    self.parseOBO()
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/obo.py", line 185, in parseOBO
    "Filename has .gz extension but is missing the gzip magic bytes.\n"
Exception: Filename has .gz extension but is missing the gzip magic bytes.
The file may be corrupted or not gzipped.

----------------------------------------------------------------------
Ran 603 tests in 11.012s

FAILED (errors=1)
````

 Furthermore, I get the same error after running the script `complete_search_with_omssa_test.py`.  This is the log:

````
 profile  ] Initializing profile LTQ XL low res
[ profile  ] 4 parameters have been updated
[  prprun  ] Preparing unode run for engine mzml2mgf_2_0_0 on file(s) tests/data/test_Creinhardtii_QE_pH8.mzML
[ set_ios  ] Setting self.io["input"]
[   Info   ] Generated engine mzml2mgf_2_0_0 output file name: /home/carlos/Software/ursgal/tests/data/test_Creinhardtii_QE_pH8.mgf
[   Info   ] convert_to_mgf_and_update_rt_lookup() scheduled on input file test_Creinhardtii_QE_pH8.mzML
[   Info   ] Reason for run: No RT lookup pickle found. Expected /home/carlos/Software/ursgal/tests/data/_ursgal_lookup.pkl
[ dmpjson  ] Preparing json dump
[ dmpjson  ] Json dumped. Path: /home/carlos/Software/ursgal/tests/data/test_Creinhardtii_QE_pH8.mgf.u.json

        -\-     mzml2mgf_2_0_0 run initialized with test_Creinhardtii_QE_pH8.mzML (Mon Sep 24 13:28:31 2018)     -/-

[   run    ] Preparing engine
[   run    ] Starting engine
[ Citation ] 
[  Please  ] 
[  cite:   ] Kremer, L. P. M., Leufken, J., Oyunchimeg, P., Schulze, S. & Fufezan, C. (2016) Ursgal, Universal Python Module Combining Common Bottom-Up Proteomics Tools for Large-Scale Analysis. J. Proteome res. 15, 788-794.
[  -----   ] 
[ Citation ] 
[ PREFLGHT ] Executing preflight sequence ...
[ prefligh ] Execution time 0.000 seconds
[ -ENGINE- ] Executing conversion ..
Converting file:
	mzml : /home/carlos/Software/ursgal/tests/data/test_Creinhardtii_QE_pH8.mzML
	to
	mgf : /home/carlos/Software/ursgal/tests/data/test_Creinhardtii_QE_pH8.mgf
Traceback (most recent call last):H8.mzML       : Processing spectrum 0
  File "tests/complete_search_with_omssa_test.py", line 65, in <module>
    force      = True
  File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 1847, in search
    force = force,
  File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 899, in convert
    output_file_name = output_file_name
  File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 351, in convert_to_mgf_and_update_rt_lookup
    force, engine_name, answer
  File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 2186, in run_unode_if_required
    json_path = json_path,
  File "/usr/local/lib/python3.6/dist-packages/ursgal/unode.py", line 1387, in run
    report['execution'] = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/ursgal/wrappers/mzml2mgf_2_0_0.py", line 71, in _execute
    precursor_max_charge  = self.params['translations']['precursor_max_charge'],
  File "/usr/local/lib/python3.6/dist-packages/ursgal/resources/platform_independent/arc_independent/mzml2mgf_2_0_0/mzml2mgf_2_0_0.py", line 113, in main
    peaks_2_write = spec.peaks('centroided')
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/spec.py", line 1017, in peaks
    mz_params = self._get_encoding_parameters('m/z array')
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/spec.py", line 199, in _get_encoding_parameters
    array_type_accession = self.calling_instance.OT[array_type]['id']
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/obo.py", line 109, in __getitem__
    self.parseOBO()
  File "/home/carlos/.local/lib/python3.6/site-packages/pymzml/obo.py", line 185, in parseOBO
    "Filename has .gz extension but is missing the gzip magic bytes.\n"
Exception: Filename has .gz extension but is missing the gzip magic bytes.
The file may be corrupted or not gzipped.
````

**Comment by StSchulze** [comment]
Hi Carlos,
I just did a fresh clone on a Linux as well as an OSX system and the don't get any failing tests.
It seems like in your case the test mzML file is somehow corrupted.
I would suggest to either clone/download ursgal again, or to download the file separately:  ursgal/tests/data/test_Creinhardtii_QE_pH8.mzML

**Comment by cguetot** [comment]
> Hi Carlos,
> I just did a fresh clone on a Linux as well as an OSX system and don't get any failing tests.
> It seems like in your case the test mzML file is somehow corrupted.
> I would suggest to either clone/download ursgal again, or to download the file separately: ursgal/tests/data/test_Creinhardtii_QE_pH8.mzML

The test runs without any issues after recent cloning. Thanks.  

On the other hand, where can I download `msgfplus2csv_py_v1_0_0`?  It wasn't installed by the `python3 install_resources.py` command.  Moreover, there isn't `url` information in its wrapper's file.

**Comment by StSchulze** [comment]
Sorry, that was my mistake, it got lost during during renaming.
It's back now (#81) as part of the git repository (therefore no url).

**Comment by cguetot** [comment]
Hi,

Thanks for your help. The `msgfplus2csv_py_v1_0_0` file issue is solved now. That's good.

On the other hand, what about the module `msgfplus2csv_v1_2_1`? It's also missing, do I have to download it manually?

best,

carlos

**Comment by JB-MS** [comment]
Hi Carlos,

yes, this has to be installed manually at the moment.

Cheers,
Johannes
