### ISSUE TITLE
Trouble running pepnovo using example script

### ISSUE THREAD

**Issue by tobymathieson** [ursgal/ursgal#83]
Hi there, I just tried to run the example script for pepnovo searching and it crashed: 

 profile  ] Initializing profile LTQ XL low res
[ profile  ] 4 parameters have been updated
[  prprun  ] Preparing unode run for engine mzml2mgf_2_0_0 on file(s) ../example_data/BSA_simple_de_novo_search/BSA1.mzML
[ set_ios  ] Setting self.io["input"]
[   Info   ] Generated engine mzml2mgf_2_0_0 output file name: /fs/local/projects/ursgal/example_data/BSA_simple_de_novo_search/BSA1.mgf
[   Info   ] Skipping convert_to_mgf_and_update_rt_lookup() on file BSA1.mzML since it was previously executed with the same input file(s) and parameters.
[   Info   ] To re-run, use convert_to_mgf_and_update_rt_lookup( force=True )
[ dmpjson  ] Preparing json dump
[ dmpjson  ] Json dumped. Path: /fs/local/projects/ursgal/example_data/BSA_simple_de_novo_search/BSA1.mgf.u.json
[ profile  ] Initializing profile LTQ XL low res
[ profile  ] 4 parameters have been updated
[  prprun  ] Preparing unode run for engine pepnovo_3_1 on file(s) /fs/local/projects/ursgal/example_data/BSA_simple_de_novo_search/BSA1.mgf
[ set_ios  ] Setting self.io["input"]
[   Info   ] Generated engine pepnovo_3_1 output file name: /fs/local/projects/ursgal/example_data/BSA_simple_de_novo_search/pepnovo_3_1/BSA1_pepnovo_3_1.csv
[   Info   ] search_mgf() scheduled on input file BSA1.mgf
[   Info   ] Reason for run: parameter "precursor_mass_tolerance_plus" was not found in previous output params....
 & Previous run was not completed, status launching
[ dmpjson  ] Preparing json dump
[ dmpjson  ] Json dumped. Path: /fs/local/projects/ursgal/example_data/BSA_simple_de_novo_search/pepnovo_3_1/BSA1_pepnovo_3_1.csv.u.json

        -\-     pepnovo_3_1 run initialized with BSA1.mgf (Wed Oct  3 14:43:34 2018)     -/-

[   run    ] Preparing engine
[   run    ] Starting engine
[ Citation ] 
[  Please  ] 
[  cite:   ] Ari M. Frank, Mikhail M. Savitski, Michael L. Nielsen, Roman A. Zubarev, and Pavel A. Pevzner (2007) De Novo Peptide Sequencing and Identification with Precision Mass Spectrometry, J. Proteome Res. 6:114-123.
[  -----   ] 
[ Citation ] 
[ PREFLGHT ] Executing preflight sequence ...

            [ WARNING ] precursor_mass_tolerance_plus and precursor_mass_tolerance_minus
            [ WARNING ] need to be combined for pyQms (use of symmetric tolerance window).
            [ WARNING ] The arithmetic mean is used.
            
[ prefligh ] Execution time 0.000 seconds
Traceback (most recent call last):
  File "simple_de_novo_search.py", line 81, in <module>
    main()
  File "simple_de_novo_search.py", line 69, in main
    force=False
  File "/fs/local/projects/ursgal/ursgal_env/lib/python3.6/site-packages/ursgal/ucontroller.py", line 1856, in search
    force      = force,
  File "/fs/local/projects/ursgal/ursgal_env/lib/python3.6/site-packages/ursgal/ucontroller.py", line 1766, in search_mgf
    force, engine_name, answer
  File "/fs/local/projects/ursgal/ursgal_env/lib/python3.6/site-packages/ursgal/ucontroller.py", line 2186, in run_unode_if_required
    json_path = json_path,
  File "/fs/local/projects/ursgal/ursgal_env/lib/python3.6/site-packages/ursgal/unode.py", line 1387, in run
    report['execution'] = self._execute()
  File "/fs/local/projects/ursgal/ursgal_env/lib/python3.6/site-packages/ursgal/wrappers/pepnovo_3_1.py", line 249, in _execute
    '''.format( self.engine, os.path.relpath(self.exe), self.execute_return_code)
AssertionError: 
  
pepnovo_3_1 crashed!

  The executable
    ../ursgal_env/lib/python3.6/site-packages/ursgal/resources/linux/64bit/pepnovo_3_1/PepNovo_bin
  terminated with Error code 1 .
  Inspect the printouts above for possible causes and verify that all input files are valid.

Not sure what I did wrong. I adapted the example_script  "simple_de_novo_search.py" by commenting out novor but that was all. 

If I try running the PepNovo from the command line it also fails :
Initializing models (this might take a few seconds)... 
Warning: no peptide composition assigner was found (e.g., LTQ_COMP/IT_TRYP)!
This may cause problems when trying to run PepNovo!

Done.
Fragment tolerance : 0.5000
PM tolernace       : 2.5000
PTMs considered    : C+57

>> 0 2442 BSA1.2442.2442.2Error: using an uninitialized peptide composition asssigner!
You might need to use an existing composition assigner.
Try adding the line: "#COMP_ASSIGNER  LTQ_COMP/IT_TRYP" to the main model file (model_name.txt)

I have never tried to run a de novo search this way before so apologies if I am doing something really stoopid.  
Toby

**Comment by StSchulze** [comment]
Hi Toby,
quick question before looking closer into it: which OS are you using? I remember pepnovo not working on all systems ...

**Comment by tobymathieson** [comment]
ah sorry for forgetting *essential* info. Linux Redhat 7, 64 bit

**Comment by StSchulze** [comment]
Alright, I tested it on CentOS 7.4 and it seems to work (except a small bug in the postflight/unify_csv that I fixed with #85).

Unfortunately, I don't have a Redhat 7 system to test it on.
One suggestion would be to download the original (http://proteomics.ucsd.edu/Software/PepNovo/) on your system and follow the instructions for installation. Might be a compiling issue.
Otherwise, I would suggest to use Novor - it's apparently faster and better anyway ;)

**Comment by tobymathieson** [comment]
Yeah, I recompiled it locally and it now works so probably a Red Hat 7 issue.
